# Generated by Django 4.0.4 on 2022-06-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mystere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individu', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_p', models.CharField(default='', max_length=255)),
                ('ind_gpe', models.CharField(default='', max_length=255)),
                ('ind_dpt', models.CharField(default='', max_length=255)),
                ('ind_initiale', models.CharField(default='', max_length=255)),
                ('numero', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiestce16.mystere')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default='', max_length=255)),
                ('numero', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiestce16.mystere')),
            ],
        ),
    ]
