# Generated by Django 4.0.4 on 2022-06-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiestce16', '0003_nuance'),
    ]

    operations = [
        migrations.AddField(
            model_name='indice',
            name='ind_commission',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='indice',
            name='ind_groupe',
            field=models.CharField(default='', max_length=255),
        ),
    ]
