# Generated by Django 5.0.2 on 2024-03-03 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiestce16", "0004_indice_ind_commission_indice_ind_groupe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indice",
            name="ind_sortant",
        ),
    ]
