# Generated by Django 4.0.4 on 2022-06-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiestce16', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indice',
            name='ind_gpe',
        ),
        migrations.AddField(
            model_name='indice',
            name='ind_sortant',
            field=models.CharField(default='', max_length=255),
        ),
    ]
