# Generated by Django 4.0.4 on 2022-06-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiestce16', '0002_remove_indice_ind_gpe_indice_ind_sortant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuance', models.CharField(default='', max_length=100)),
                ('numero', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiestce16.mystere')),
            ],
        ),
    ]
